In [54]:
import numpy as np
#
print("Question 1: ")
a = np.random.randint(1, 20, 15) #declare array with random values from 1 to 20 of size 15
print(f"Array A = {a}")
b = a.reshape(3, 5) #reshape array A
print("Array A reshaped as array B to be a 3 by 5: ")
print(b)
print(f"Shape of array B = {b.shape}") #print shape of resized Array (b)

print("\nNew array B with maximum values of each column replaced with 0: ")
b[b == b.max(axis=0)] = 0 #set the maximum values of every column with 0
print(b)

Question 1: 
Array A = [ 6  4  6 11  5  9  6  1 10 19  5 10  2 13  1]
Array A reshaped as array B to be a 3 by 5: 
[[ 6  4  6 11  5]
 [ 9  6  1 10 19]
 [ 5 10  2 13  1]]
Shape of array B = (3, 5)

New array B with maximum values of each column replaced with 0: 
[[ 6  4  0 11  5]
 [ 0  6  1 10  0]
 [ 5  0  2  0  1]]


In [51]:
import numpy as np
#
print("Question 2: ")
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], np.int32) #force the data type to be 4-byte integer elements
print(c)
print(f"Shape of array c = {c.shape}") #display the shape
print(f"Datatype of array c = {c.dtype}") #display the data type

Question 2: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array c = (3, 4)
Datatype of array c = int32


In [55]:
import numpy as np
#
print("Question 3: ")
given_array = np.array([[0, 1, 2], [3, 4, 5]]) #create given array
print(f"Given array: ")
print(given_array)
sum_diagonal = given_array.trace()
print(f"The sum of the diagonal elements is {sum_diagonal}") #print the sum of the diagonal elements using .trace() function

Question 3: 
Given array: 
[[0 1 2]
 [3 4 5]]
The sum of the diagonal elements is 4


In [56]:
import numpy as np
#
print("Question 4: ")
print("Arrays of Odds and Evens: ")
print(np.arange(10, 71, 1)) #create evens and odds between 10 and 70

print("\nElement-wise operations: ")
print("Array 1: ")
array_1 = np.array([[5, 20, 3, 9],
                    [14, 2, 19, 8],
                    [10, 7, 13, 25]])
print(array_1)
print("\nArray 2: ")
array_2 = np.array([[12, 11, 19, 4],
                    [9, 5, 2, 17],
                    [18, 15, 14, 13]])
print(array_2)

#perform multiple element-wise operations using two arrays of same size
print(f"\nArray 1 + Array 2 = ")
print(array_1 + array_2)
print("\nArray 1 * Array 2 = ")
print(array_1 * array_2)
print("\nArray 1 - Array 2 = ")
print(array_1 - array_2)

print("\nSort an array by row and column in ascending order: ")
given_array = np.array([[5.54, 3.38, 7.99],
                        [3.54, 4.38, 6.99],
                        [1.54, 2.39, 9.29]]) #
print("Given array: ")
print(given_array)

print("\nSorted array in ascending order: ")
sorted_array = np.sort(given_array, axis=0) #Utilize the .sort function, sorting from the first axis
print(sorted_array)

Question 4: 
Arrays of Odds and Evens: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70]

Element-wise operations: 
Array 1: 
[[ 5 20  3  9]
 [14  2 19  8]
 [10  7 13 25]]

Array 2: 
[[12 11 19  4]
 [ 9  5  2 17]
 [18 15 14 13]]

Array 1 + Array 2 = 
[[17 31 22 13]
 [23  7 21 25]
 [28 22 27 38]]

Array 1 * Array 2 = 
[[ 60 220  57  36]
 [126  10  38 136]
 [180 105 182 325]]

Array 1 - Array 2 = 
[[ -7   9 -16   5]
 [  5  -3  17  -9]
 [ -8  -8  -1  12]]

Sort an array by row and column in ascending order: 
Given array: 
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sorted array in ascending order: 
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [57]:
import numpy as np

#
print("Question 5: ")
print("Finding false values: ")

nan = 6
print("\nGiven Array: ")
given_array = np.array([[4, 2, np.nan, 1],
                        [11, 12, 14, 9],
                        [5, np.nan, 1, np.nan]])

print(given_array)
print("\nFinding the missing data of the given array: ")
print(np.isnan(given_array))

Question 5: 
Finding false values: 

Given Array: 
[[ 4.  2. nan  1.]
 [11. 12. 14.  9.]
 [ 5. nan  1. nan]]

Finding the missing data of the given array: 
[[False False  True False]
 [False False False False]
 [False  True False  True]]
